GITHOME = https://github.com/ponyatov/jsUML2/raw/master/build

files: css/UDStyle.css UDCore.js UDModules.js

UDCore.js:
	wget -c $(GITHOME)/$@

UDModules.js:
	wget -c $(GITHOME)/$@

css/UDStyle.css:
	wget -c -P css $(GITHOME)/css/UDStyle.css

